### ISSUE TITLE
Use Nodesource PPA

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/ansible-role-nodejs#1]
Ubuntu uses a very old version of nodejs.  We want to be able to install the latest version.  We should also go ahead and install PM2 to manage individual web applications on a host.

**Comment by charlesbrandt** [comment]
What's the benefit of this approach over something like nvm? https://github.com/creationix/nvm

**Comment by inghamn** [comment]
This means we'll get node updates from Nodesource during Ubuntu's automated upgrades

**Comment by charlesbrandt** [comment]
I have concerns about automatically deploying new versions of node to an application in production without testing the new version through a full release cycle.

**Comment by inghamn** [comment]
The major version of node won't change. We can pick Node 8 or Node 10, and stick with that.  But we'll be getting updates to that node version.
